#!/usr/bin/env bash
# Idempotent dev-environment bootstrap for calc.figurebase.ru (Flask).
# Safe to run repeatedly: only creates what is missing.
set -euo pipefail

cd "$(dirname "$0")/.."
echo "==> Project root: $(pwd)"

# 1. Ensure python venv support is available (Debian/Ubuntu split it out).
if ! python3 -c "import ensurepip" >/dev/null 2>&1; then
  echo "==> Installing python3-venv (ensurepip missing)"
  sudo apt-get update -qq
  sudo apt-get install -y -qq python3-venv
fi

# 2. Create the virtualenv once, then keep it up to date.
if [ ! -x ".venv/bin/python" ]; then
  echo "==> Creating virtualenv at .venv"
  python3 -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate

echo "==> Installing Python dependencies"
python -m pip install --upgrade pip -q
pip install -r requirements.txt

# 3. Provide a local .env for development if one is not present.
#    These are non-production placeholder values for an isolated dev VM only.
if [ ! -f ".env" ]; then
  echo "==> Writing development .env"
  cat > .env <<'ENV'
# Local development configuration (generated by .cursor/install.sh).
# NOT for production. Never commit this file.
FLASK_APP=app.py
FLASK_ENV=development

# Strict security mode is satisfied by a secret key + a reader password.
SECRET_KEY=dev-only-secret-key-not-for-production-0123456789abcdef
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
SITE_READ_PASSWORD=judge

# SQLite database stored in the project root.
DATABASE_URL=sqlite:///figure_skating.db

LOG_LEVEL=INFO
LOG_FILE=logs/app.log

# Google Sheets integration disabled in dev (no service-account credentials).
GOOGLE_CREDENTIALS_PATH=
ENV
fi

# 4. Runtime directories used by the app.
mkdir -p logs uploads instance

# 5. Initialize the SQLite schema. The initial Alembic migration is a no-op,
#    so tables are created from the models via create_all (idempotent), then
#    the migration history is stamped to head.
echo "==> Initializing database schema"
python - <<'PY'
from app_factory import create_app
from extensions import db
app = create_app()
with app.app_context():
    db.create_all()
PY
flask db stamp head >/dev/null 2>&1 || true

echo "==> Install complete."
